#!/bin/sh
if mountpoint -q /target; then
    echo "Installing to /target"
    cp /root/rpmbuild/RPMS/x86_64/perp-*.rpm /target
else
    echo "/target is not a mountpoint."
    echo "re-run this container with -v \$PWD:/target"
    echo "and it will be copied to your current dir"
fi
